name: Build

on:
  push:
    tags: [ "v*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: ${{ startsWith(github.ref, 'refs/tags/') }}
      matrix:
        os: [macos-latest, windows-latest]

    env:
      BUILD_TYPE: RelWithDebInfo

    steps:
    - name: Configure Xcode
      if: runner.os == 'MacOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build

    - name: Build
      run: cmake --build build --config $BUILD_TYPE

    - name: Upload built plug-ins
      uses: actions/upload-artifact@v4
      with:
        path: dist/
        name: built-plugins-${{ matrix.os }}

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
    - name: Download built plug-ins
      uses: actions/download-artifact@v4
      with:
        pattern: built-plugins-*
        merge-multiple: true
        path: plugin/

    - name: Zip plug-ins
      working-directory: plugin/
      run: |
        mkdir ../dist
        ls -lR .
        for p in *; do zip -r ../dist/$p.zip $p; done

    - name: Extract release notes
      run: |
        tag_url=$(curl https://api.github.com/repos/${{ github.repository }}/git/${{ github.ref }} | jq -r '.object.url')
        curl $tag_url | jq -r '.message' | tail -n +3 | tee changelog.md

    - name: Attach zipped plug-ins to release
      uses: softprops/action-gh-release@v2
      with:
        body_path: changelog.md
        files: dist/*
