name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    env:
      BUILD_TYPE: RelWithDebInfo

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build

    - name: Build
      shell: bash
      run: cmake --build build --config $BUILD_TYPE

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: built-plugins-${{ matrix.os }}

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        pattern: built-plugins-*
        merge-multiple: true

    - name: Extract release notes
      run: git cat-file tag ${{ github.ref }} | tail -n +3 > changelog.md

    - name: Attach binaries to release
      uses: softprops/action-gh-release@v2
      with:
        body_path: changelog.md
        files: |
          *.vst3
          *.component


